# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty32"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.ssh.private_key_path = "/Users/john/.ssh/insecure_private_key"
  config.ssh.insert_key = false 
  config.vm.provider :virtualbox do |vb|
	vb.customize [ 'modifyvm', :id, '--memory', '512' ]
	vb.customize [ 'modifyvm', :id, '--cpus', '2' ]
	vb.customize [ 'modifyvm', :id, '--name', 'forwarded' ]
  end
end
