# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.provider :virtualbox do |vb|
	vb.customize [ 'modifyvm', :id, '--memory', '512' ]
	vb.customize [ 'modifyvm', :id, '--cpus', '2' ]
  end
end
