Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/xenial64"
  config.vm.hostname = "dockervm"
  config.vm.provider :virtualbox do |vb|
        vb.customize [ 'modifyvm', :id, '--cpus', '1', '--name', 'dockervm', '--memory', '386' ]
  end
  config.vm.provision "docker",
    images: ["ubuntu"]
end

