# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/trusty32"
  config.vm.provision "shell", path: "script.sh"
  config.ssh.private_key_path = "/Users/john/.ssh/insecure_private_key"
  config.ssh.insert_key = false 
end
