# -*- mode: ruby -*-
# vi: set ft=ruby :
BOX="ubuntu/focal64"
RAM="2048"
CPUS="2"
Vagrant.configure("2") do |config|
  config.vm.box = BOX
  config.vm.provision "shell", path: "install_docker_tools.sh"
  config.vm.provision "shell", path: "install_sysbox.sh"
  config.vm.hostname = "dind"
  config.vm.provider :virtualbox do |vb|
    vb.customize [ 'modifyvm', :id, '--memory', RAM ]
    vb.customize [ 'modifyvm', :id, '--cpus', CPUS ]
    vb.customize [ 'modifyvm', :id, '--name', 'docker-in-docker' ]
  end
end
